import turtle

Ross = turtle.Turtle()
Rachel = turtle.Turtle()
Chandler = turtle.Turtle()
Monica = turtle.Turtle()
Phoebe = turtle.Turtle()

Ross.shape("turtle")
Rachel.shape("turtle")
Chandler.shape("turtle")
Monica.shape("turtle")
Phoebe.shape("turtle")

Monica.fillcolor("light blue")
Monica.begin_fill()
Monica.forward(800)
Monica.backward(1800)
Monica.left(90)
Monica.forward(800)
Monica.right(90)
Monica.forward(1800)
Monica.right(90)
Monica.forward(800)
Monica.end_fill()
